# Auto-generated by setup.bat
$env:Path = 'C:\Tools\tools\python;C:\Tools\tools\tesseract;C:\Tools\tools\ffmpeg;C:\Tools\tools\pandoc;C:\Tools\tools\wkhtmltopdf;' + $env:Path
$exe = 'C:\Tools\.venv\Scripts\python.exe'
$script = 'C:\Tools\mcp_fs_server.py'
$workdir = 'C:\Tools\'
$pidFile = 'C:\Tools\.venv\server.pid'
$p = Start-Process -FilePath $exe -ArgumentList ('"' + $script + '"') -WorkingDirectory $workdir -WindowStyle Hidden -PassThru
$p.Id | Out-File -FilePath $pidFile -Encoding ASCII
